apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstoneaws
  labels:
    app: capstoneaws
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstoneaws
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstoneaws
    spec:
      containers:
        - image: docsudhachand/capstoneaws:2.0
          imagePullPolicy: Always
          name: capstoneaws
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: capstoneaws
  labels:
    app: capstoneaws
spec:
  type: LoadBalancer
  selector:
    app: capstoneaws
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP