apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone
  labels:
    app: capstone
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstone
    spec:
      containers:
        - image: docsudhachand/capstone:1.0
          imagePullPolicy: Always
          name: capstone
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: capstone
  labels:
    app: capstone
spec:
  type: LoadBalancer
  selector:
    app: capstone
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP